version: '3.8'

services:
  # Lumen application container
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: sh -c "composer install && php -S 127.0.0.1:8001"
    ports:
      - '8001:8000'
    depends_on:
      - redis-mail
      - nginx-mail

  # Redis service
  redis-mail:
    image: redis:latest
    ports:
      - '6380:6379'

  nginx-mail:
    image: nginx:1.19
    volumes:
      - ./public:/var/www/html
    ports:
      - "82:80"
